[tool.poetry]
name = "openfight"
version = "0.1.1"
description = "A web scraping script for the UFC website."
authors = ["mtttech <mtaylor9754@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
